mybatis:
  mapper-locations: classpath*:/mybatis/*Mapper.xml

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/student
    password: password

  server:
    error:
      include-message: always